---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: webapps   # Specify the namespace for the Secret
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGd1YTFmNmlrCg==
  CLOUDINARY_KEY: NzUzNzQ3NDUzNjQ0Nzk3Cg==
  CLOUDINARY_SECRET: U2s2bGtyS05LcnZCZ0JBdENwbkRBLU9VS01ZCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2lZbWxuWkdWMklpd2lZU0k2SW1Oc2RuTTRNR3gzWkRCME16a3lhbTV1YkdkbmIyMTZlWGNpZlEuMmZfbWlBcjhjNE11VEpTRUtEZzdNZwo=
  DB_URL: bW9uZ29kYitzcnY6Ly91em9uZHVlZ2JvbWJhaDQxOTpPT0M3QmE1NWhPWDkyM0paQGJpZ2RldnkuOTNoY3hldi5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9YmlnZGV2eQo=
  SECRET: QmlnZGV2Cg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: webapps   # Specify the namespace for the Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: uzondu/ralphprod:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: webapps   # Specify the namespace for the Service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
                
